# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-29 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBSEMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveSmallIntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='funds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
